### PR TITLE
Webextension build.

### LINKED ISSUE #14: [Request] Offer as a webextension too?
The reason I ask is that I'm trying to migrate away from userscripts and towards extensions. The only linkifying webextension available for Firefox is [this one](https://addons.mozilla.org/en-US/firefox/addon/linkificator/) but it is slower than your script. So wondering if you have considered / are interested in releasing as a webextension too?

### PR DESCRIPTION
**Pull request by eight04**
Fixes #14.

### CODE REVIEW

**Comment by eight04** [comment]
@FatOrangutan Would you like to test out this branch?

**Comment by FatOrangutan** [comment]
Sure!

Seems to work pretty well from some quick tests (on Firefox Nightly). Some issues, mostly around its presentation as an add-on that you probably already know about:

* When I tried importing settings from the userscript, I got an error saying: `can't convert undefined to object`. fwiw, these were the settings that the userscript (installed through Violentmonkey) had exported:  
  
`{"ip":true,"image":true,"imageSkipSelector":".hljs, .highlight, .brush\\:","unicode":false,"newTab":false,"standalone":false,"boundaryLeft":"{[(\"'","boundaryRight":"'\")]},.;?!","skipSelector":".highlight, .editbox, .brush\\:, .bdsug, .spreadsheetinfo, #view-code, .prettyprint, code, .addon","selector":"li","timeout":10000,"maxRunTime":100,"customRules":""}`

* Most add-ons typically include their own name in `browser_action`'s `default_title`. The current title of `Configure` might be ambigious.
* Maybe add a page action for the "configure settings for this domain" feature?

I'll let you know if I come across any other issues.

**Comment by eight04** [comment]
> When I tried importing settings from the userscript, I got an error saying: can't convert undefined to object

I'm sure this is unfixable and this will be the breaking change. Previously, we use [GM_config](https://github.com/eight04/GM_config) to handle configuration, but the import/export feature in `GM_config` can only import/export settings under the current domain. In this branch, we switched to [webext-pref](https://github.com/eight04/webext-pref)/[GM_webextPref](https://github.com/eight04/GM_webextPref) which can import/export the entire database.

This would also affect userscript version when the change is landed.

> Most add-ons typically include their own name in browser_action's default_title. The current title of Configure might be ambigious.

:+1: 

> Maybe add a page action for the "configure settings for this domain" feature?

Do you mean [browser.pageAction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction)?

> I installed it in Chrome

To support Chrome, we have to add [browser-polyfill](https://github.com/mozilla/webextension-polyfill).

**Comment by eight04** [comment]
Native dialogs are unavailable in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=476350

**Comment by eight04** [comment]
> open the options page defaulting to the global settings view and the page action to open it defaulting to the per domain settings of the current domain.

Currently, when you click on the browser button and click the "+" button, the "Add new domain" prompt would be pre-filled with the current domain. I'm not sure if it is intuitive enough.

**Comment by eight04** [comment]
> The current title of Configure might be ambigious.

It has been changed to "Linkify Plus Plus Options".

> Chrome

Fixed. Now the extension can be installed and run in Chrome. Chrome would still warn about unknown manifest properties but it shouldn't harm.

**Comment by FatOrangutan** [comment]
>Currently, when you click on the browser button and click the "+" button, the "Add new domain" prompt would be pre-filled with the current domain. I'm not sure if it is intuitive enough.

It makes sense (and is convenient!) after trying it once, but maybe add an on-hover tooltip to the two buttons of `x` and `+`. There might also be enough space to just replace the symbols with full text e.g. `Add new button` instead of `+`. Maybe move the two buttons to be in the next line after the dropdown if it feels cramped up.

>Now the extension can be installed and run in Chrome.

Can confirm, the options page works now.

BTW, do you have any plans for a toolbar icon? I'm not a designer but I might be able to help a bit if you want. One idea that I had was having a capital L (for the extension name, and also signifies text) with a blue underline underneath (for link). Something like this:
capture 3
Here is the svg if you want:
`<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
	<path fill="#4c4c4d" d="M3.5 1a.5.5 0 1 0 0 1H4v9h-.5a.5.5 0 0 0 0 1h7.855a.5.5 0 0 0 .475-.184.5.5 0 0 0 .106-.398V10.5a.5.5 0 1 0-1 0v.5H6V2h.5a.5.5 0 1 0 0-1h-3z"/>
	<path fill="#45a1ff" d="M2.5 14a1 1 0 1 0 0 2h11a1 1 0 1 0 0-2h-11z"/>
</svg>
`

**Comment by eight04** [comment]
> It makes sense (and is convenient!) after trying it once, but maybe add an on-hover tooltip to the two buttons of x and +. There might also be enough space to just replace the symbols with full text e.g. Add new button instead of +. Maybe move the two buttons to be in the next line after the dropdown if it feels cramped up.

Added tooltips. I've tried to replace the icon with the text, but the button is too large compared to the "Current domain" dropdown.

> Here is the svg if you want

I really like it :+1: I've also used it as the icon of the userscript.

**Pull request merged**
