### PR TITLE
Support file:// URIs

### PR DESCRIPTION
**Pull request by specious**
file-uri-support

### CODE REVIEW

**Comment by eight04** [comment]
Would it be better to `// @include *`?

**Comment by specious** [comment]
I'm by no means an expert, but I see some userscripts specify `// @include *://*`.

**Comment by eight04** [comment]
It won't work with data URI like `data:text/html...`.

**Comment by specious** [comment]
With the change in 850ad9760135036e08fb36ca4aa9af25a5dc9357 to `// @include *` the linkifier is no longer activated on file:// URIs:

linkify-not-activated

I tried with `// @include *://*` and it works.

**Comment by eight04** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/331

**Comment by eight04** [comment]
Fixed wiith Tampermonkey 4.2.5353.

**Pull request closed without merging**
